### ISSUE TITLE
Unclosed group near index 26 (Regex concering Comms.properties)

### ISSUE THREAD

**Issue by wipedx** [Deltik/SignEdit#11]
Hey, I've encountered an issue when utilizing the plugin. Note that the log is from v1.11.0, but v1.11.1 ends with the same message. 

`[22:22:31] [Server thread/ERROR]: Error occurred while enabling SignEdit v1.11.0 (Is it up to date?)                                                                           java.util.regex.PatternSyntaxException: Unclosed group near index 26                                                                                                           (^|.*\)Comms.*\.properties                                                                                                                                                             at java.util.regex.Pattern.error(Pattern.java:2015) ~[?:?]                                                                                                                     at java.util.regex.Pattern.accept(Pattern.java:1873) ~[?:?]                                                                                                                    at java.util.regex.Pattern.group0(Pattern.java:3048) ~[?:?]                                                                                                                    at java.util.regex.Pattern.sequence(Pattern.java:2111) ~[?:?]                                                                                                                  at java.util.regex.Pattern.expr(Pattern.java:2056) ~[?:?]                                                                                                                      at java.util.regex.Pattern.compile(Pattern.java:1778) ~[?:?]                                                                                                                   at java.util.regex.Pattern.<init>(Pattern.java:1427) ~[?:?]                                                                                                                    at java.util.regex.Pattern.compile(Pattern.java:1068) ~[?:?]                                                                                                                   at org.deltik.mc.signedit.UserComms.getResourceNamesFromSelf(UserComms.java:111) ~[?:?]                                                                                        at org.deltik.mc.signedit.UserComms.removeOldOriginals(UserComms.java:138) ~[?:?]                                                                                              at org.deltik.mc.signedit.UserComms.deploy(UserComms.java:91) ~[?:?]                                                                                                           at org.deltik.mc.signedit.SignEditPlugin.onEnable(SignEditPlugin.java:65) ~[?:?]                                                                                               at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.15.2.jar:git-Spigot-c574e08-d171d7e]                                                           at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [spigot-1.15.2.jar:git-Spigot-c574e08-d171d7e]                                              at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:432) [spigot-1.15.2.jar:git-Spigot-c574e08-d171d7e]                                             at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [spigot-1.15.2.jar:git-Spigot-c574e08-d171d7e]                                               at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [spigot-1.15.2.jar:git-Spigot-c574e08-d171d7e]                                              at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [spigot-1.15.2.jar:git-Spigot-c574e08-d171d7e]                                                    at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274) [spigot-1.15.2.jar:git-Spigot-c574e08-d171d7e]                                                 at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-c574e08-d171d7e]                                                  at java.lang.Thread.run(Thread.java:835) [?:?]   `

**Comment by Deltik** [comment]
Hi @wipeDx,

Thanks for reporting this bug!  It appears to be an oversight affecting Microsoft Windows platforms.  I'll release a fix for this soon.

**Comment by wipedx** [comment]
If there is anything I can help to debug, just mention it!

**Comment by Deltik** [comment]
Actually, @wipeDx, since I don't have a Windows machine handy right now, could you test this development build for me to make sure that the issue is fixed?:

~[SignEdit-1.11.2-SNAPSHOT.jar.zip](https://github.com/Deltik/SignEdit/files/4240377/SignEdit-1.11.2-SNAPSHOT.jar.zip)~ **Edit:** This snapshot does not fix the bug.

**Comment by wipedx** [comment]
Sure thing, I will do that tommorow first thing in the morning!

**Comment by Deltik** [comment]
@wipeDx: Actually, I found a Windows system and tested the bugfix on it.  A release is building now!

**Comment by Deltik** [comment]
[SignEdit for Bukkit v1.11.2](https://github.com/Deltik/SignEdit/releases/tag/v1.11.2) has been released!  You can download it directly [here](https://github.com/Deltik/SignEdit/releases/download/v1.11.2/SignEdit-1.11.2.jar).

As far as I can tell, the plugin now runs on Microsoft Windows.

**Comment by wipedx** [comment]
Hey @Deltik,
Seems like there's still an issue with spaces within plugin path's and windows not recognizing %20 as space!

```
[09:15:17] [Server thread/ERROR]: Error occurred while enabling SignEdit v1.11.2 (Is it up to date?)
java.lang.Error: java.nio.file.NoSuchFileException: V:\Minecraft%20Server%20Spigot\plugins\SignEdit-1.11.2.jar
	at org.deltik.mc.signedit.ResourceList.getResourcesFromJarFile(ResourceList.java:76) ~[?:?]
	at org.deltik.mc.signedit.ResourceList.getResources(ResourceList.java:61) ~[?:?]
	at org.deltik.mc.signedit.UserComms.getResourceNamesFromSelf(UserComms.java:111) ~[?:?]
	at org.deltik.mc.signedit.UserComms.removeOldOriginals(UserComms.java:136) ~[?:?]
	at org.deltik.mc.signedit.UserComms.deploy(UserComms.java:91) ~[?:?]
	at org.deltik.mc.signedit.SignEditPlugin.onEnable(SignEditPlugin.java:65) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.15.2.jar:git-Spigot-8faa8b4-fba9f48]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [spigot-1.15.2.jar:git-Spigot-8faa8b4-fba9f48]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:432) [spigot-1.15.2.jar:git-Spigot-8faa8b4-fba9f48]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [spigot-1.15.2.jar:git-Spigot-8faa8b4-fba9f48]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [spigot-1.15.2.jar:git-Spigot-8faa8b4-fba9f48]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [spigot-1.15.2.jar:git-Spigot-8faa8b4-fba9f48]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274) [spigot-1.15.2.jar:git-Spigot-8faa8b4-fba9f48]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-8faa8b4-fba9f48]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.nio.file.NoSuchFileException: V:\Minecraft%20Server%20Spigot\plugins\SignEdit-1.11.2.jar
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53) ~[?:?]
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:198) ~[?:?]
	at java.nio.file.Files.readAttributes(Files.java:1840) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1160) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:719) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:239) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:169) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:183) ~[?:?]
	at org.deltik.mc.signedit.ResourceList.getResourcesFromJarFile(ResourceList.java:72) ~[?:?]
	... 14 more                                                                
```
(Apparently, Windows also doesn't honor line breaks and just copies this as one line ...)

EDIT: when running in a spaceless folder, it works:
![image](https://user-images.githubusercontent.com/10381133/75106653-23092c00-561f-11ea-89a4-9b6f03f6dcbf.png)

**Comment by Deltik** [comment]
@wipeDx: This is a separate issue, which I'm now tracking in #12.
